// client/scenarios/scenarios.js
// 客戶端劇本配置 — R0 初始故事 + Profile 預設值 + UI 設定

export const SCENARIOS = {
    wuxia: {
        id: 'wuxia',
        milestoneIds: ['M1_WORLD_AWARENESS','M2_FIRST_CLUE','M3_KEY_NPC','M4_ANCIENT_KNOWLEDGE','M5_OBSTACLE','M6_BREAKTHROUGH','M7_FINAL_PREPARATION','M8_HOMECOMING'],
        milestoneChars: ['符','文','漸','次','浮','現','歸','途'],
        suggestionPrefix: '書僮小聲說：',
        questJournalDefault: '手中的紙條寫著：「尋找回家的方法」',
        name: '武俠',
        themeClass: '',
        defaultProfile: { yearName: '元祐', year: 1, month: 1, day: 1, timeOfDay: '上午' },
        moralityLabels: { positive: '正', negative: '邪', axis: '立場傾向' },
        milestoneDisplay: { title: '歸途印記', description: '集齊八枚即可回家' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '莫名其妙的穿越',
            story: `你睜開眼睛。\n\n頭頂是一片刺眼的藍天，身下是一堆扎人的乾草。空氣裡飄著一股你完全無法辨認的味道——像是有人把中藥房和燒烤攤強行混在一起。\n\n你猛地坐起來，四周是一條塵土飛揚的泥巴路，兩旁是低矮的土牆和掛著褪色布簾的店鋪。遠處傳來雞鳴狗吠，還有一個大嬸扯著嗓子罵誰家的孩子偷了她晾的蘿蔔乾。\n\n這絕對不是你的房間。\n\n你低頭一看——身上穿著一件灰撲撲的粗布衣裳，腳上是一雙草鞋，左邊那隻還破了個洞。你完全不記得自己是怎麼到這裡的。\n\n然後你發現右手緊緊攥著一張皺巴巴的紙條：「任務：尋找回家的方法。」\n\n紙條背面：「附註：別死了，死了就真回不去了。」\n\n一個挑著扁擔的老大爺正好路過，用一種看傻子的眼神瞟了你一眼。`,
            WRD: '大晴天，熱得要命',
            LOC: ['梁國', '東境', '臨川', '無名村'],
            PC: `${username}剛穿越，一臉懵，手握紙條。`,
            NPC: [],
            timeOfDay: '上午',
            morality: 0,
            yearName: '元祐', year: 1, month: 1, day: 1,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '先搞清楚這是哪裡。'
        }),
    },

    school: {
        id: 'school',
        milestoneIds: ['M1_AWAKENING','M2_SYSTEM_GLITCH','M3_ALLIES','M4_PROTAGONIST','M5_ADMIN_TRACE','M6_REBELLION','M7_CONFRONTATION','M8_EXIT_GAME'],
        milestoneChars: ['學','分','逐','步','集','滿','畢','業'],
        suggestionPrefix: '直覺告訴你：',
        questJournalDefault: '課本封面寫著：「角色定位：無劇情路人」',
        name: '學園',
        themeClass: 'school-theme',
        defaultProfile: { yearName: '', year: 0, month: 4, day: 8, timeOfDay: '上午課' },
        moralityLabels: { positive: '秩序', negative: '自由', axis: '行事風格' },
        milestoneDisplay: { title: '畢業學分', description: '集滿八學分即可登出' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '醒來發現自己是NPC',
            story: `頭好痛。\n\n你緩緩睜開眼，映入眼簾的是……日光燈。以及天花板上一個可疑的水漬。\n\n等等。\n\n你不是在加班嗎？報表還沒交、客戶明天要開會、咖啡才喝了第三杯——然後就什麼都不記得了。\n\n「同學，你又在上課睡覺。」\n\n一個中年男人的聲音。你轉頭一看：黑板、講台、穿制服的學生。你坐在窗邊倒數第三排。\n\n……你回到高中了？\n\n不對。你低頭看自己的手——年輕、白淨、完全不是你每天敲鍵盤敲到長繭的手。桌上的課本寫著「私立青嵐高中 二年三班」。\n\n你的名字呢？翻開課本封面——\n\n「${username}」。\n\n旁邊還有一行小字，像是被什麼東西壓印上去的：\n\n**『角色定位：無劇情路人。無台詞、無事件、無攻略價值。』**\n\n窗外陽光燦爛，櫻花飄落，一切看起來都很美好。\n\n只是——圍牆外面的景色，好像還沒載入完畢。`,
            WRD: '晴天，微風，櫻花季',
            LOC: ['私立青嵐高中', '教學大樓', '二年三班教室'],
            PC: `${username}剛在課堂上醒來，發現自己是遊戲裡的路人NPC。`,
            NPC: [],
            timeOfDay: '上午課',
            morality: 0,
            yearName: '', year: 0, month: 4, day: 8,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '課本上寫著你是「無劇情路人」。也許該先看看這個學校到底是什麼地方。'
        }),
    },

    mecha: {
        id: 'mecha',
        milestoneIds: ['M1_AWAKENING_IN_IRON','M2_FIRST_SYNC','M3_ECHO_FRAGMENT','M4_TRUTH_OF_THE_RIFT','M5_BETRAYAL','M6_RESONANCE','M7_EVE_OF_DECISION','M8_BEYOND_THE_RIFT'],
        milestoneChars: ['鐵','殼','裡','的','心','跳','迴','響'],
        suggestionPrefix: '始核低語：',
        questJournalDefault: '始核同調卡背面寫著：「若持有者死亡，始核將進入休眠」',
        name: '機甲',
        themeClass: 'mecha-theme',
        defaultProfile: { yearName: '新曆', year: 47, month: 3, day: 14, timeOfDay: '第一班哨' },
        moralityLabels: { positive: '共感', negative: '理性', axis: '同調傾向' },
        milestoneDisplay: { title: '同調印記', description: '八段迴響全部覺醒時，裂隙彼方的門將開啟' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '鐵殼裡醒來的人',
            story: `頭痛。劇烈的頭痛。\n\n你睜開眼。\n\n映入眼簾的不是天花板，而是一圈環繞你的半透明螢幕，上面跳動著你完全看不懂的數據流。你的雙手插在兩個凝膠狀的操控球裡，背後有什麼東西貼著你的脊椎，微微發熱。\n\n「……同調率穩定，生命特徵正常。」一個冰冷的女聲從通訊器傳來。「零號機，請回報駕駛員狀態。」\n\n螢幕上方用紅色粗體字閃爍著：\n\n【始核同調鎖定完成。綁定不可逆。】\n\n「等一下，」你終於發出聲音，「什麼叫『不可逆』？」\n\n沒有人回答你。但你的脊椎後方那個發熱的裝置，溫度又升高了一點——像是某個東西在回應你。\n\n而且它感覺很……寂寞。`,
            WRD: '鐵灰色天空，天裂微微發紅',
            LOC: ['暮雲城', '零號格納庫', '駕駛艙'],
            PC: `${username}剛穿越，被綁定在零號律體駕駛艙內，一臉懵。`,
            NPC: [],
            timeOfDay: '第一班哨',
            morality: 0,
            yearName: '新曆', year: 47, month: 3, day: 14,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '你被困在巨型機器的駕駛艙裡，螢幕上說「綁定不可逆」。通訊器那頭有人在等你回話。'
        }),
    },

    modern: {
        id: 'modern',
        milestoneIds: ['M1_WRONG_WORLD','M2_GLITCH_SPOTTED','M3_INFORMANT','M4_FREQUENCY_MAP','M5_CONVERGENCE','M6_RESONANCE_KEY','M7_LAST_NIGHT','M8_CROSSING_BACK'],
        milestoneChars: ['錯','頻','的','城','市','在','呼','喚'],
        suggestionPrefix: '直覺低語：',
        questJournalDefault: '手機備忘錄寫著：「這不是你的世界——找到回去的路」',
        name: '現代',
        themeClass: 'modern-theme',
        defaultProfile: { yearName: '', year: 0, month: 9, day: 17, timeOfDay: '早晨通勤' },
        moralityLabels: { positive: '人情', negative: '務實', axis: '處世態度' },
        milestoneDisplay: { title: '跨頻碎片', description: '收集八片碎片即可打開回家的門' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '錯頻的早晨',
            story: `鬧鐘響了。\n\n你伸手拍掉床頭那支手機，螢幕亮起：07:15，星期三。\n\n一切都很正常。你打了個呵欠，踢開棉被，光腳踩上冰涼的磁磚地板——然後愣住了。\n\n你的房間是木地板。\n\n你緩緩環顧四周。格局對、傢俱對、窗簾的顏色對，但地板是白色磁磚。你揉揉眼睛，沒變。\n\n「……裝潢公司半夜來施工？」你嘟囔著走進浴室，打開水龍頭。鏡子裡的臉是你自己，看起來沒少什麼零件。\n\n你擠了牙膏——\n\n**「好來」**。\n\n你盯著那管牙膏看了五秒。你用的牌子明明叫「黑人」。不對，「好來」是什麼時候改的名？還是你記錯了？\n\n帶著一肚子困惑出了門。捷運站入口的招牌寫著「市政府站」，人潮和平常一樣洶湧。但你掏出悠遊卡的瞬間，閘門上的Logo讓你整個人僵在原地。\n\n那個Logo……你從來沒見過。\n\n後面的上班族不耐煩地咂嘴。你機械性地刷卡進站，腦子裡只有一個念頭：\n\n這裡到底是哪裡？`,
            WRD: '陰天，悶熱，有雷雨預報',
            LOC: ['台北', '信義區', '市政府站'],
            PC: `${username}剛在自己的房間醒來，但所有細節都微妙地「不對」。`,
            NPC: [],
            timeOfDay: '早晨通勤',
            morality: 0,
            yearName: '', year: 0, month: 9, day: 17,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '一切看起來都很正常，但又處處不對。也許該先冷靜下來，觀察一下這個「台北」到底哪裡不一樣。'
        }),
    },

    animal: {
        id: 'animal',
        milestoneIds: ['M1_BEAST_AWAKENING','M2_TERRITORY_CLUE','M3_ELDER_CONTACT','M4_SPIRIT_LORE','M5_GREAT_BARRIER','M6_PACK_UNITED','M7_SPIRIT_GATE','M8_RETURN_PATH'],
        milestoneChars: ['翠','谷','靈','域','魂','渡','歸','野'],
        suggestionPrefix: '獸的直覺告訴你：',
        questJournalDefault: '腦海中的聲音說：「尋找回到人類身體的方法」',
        name: '動物',
        themeClass: 'animal-theme',
        defaultProfile: { yearName: '靈紀', year: 1, month: 3, day: 1, timeOfDay: '晨露' },
        moralityLabels: { positive: '共生', negative: '獨行', axis: '生存本能' },
        milestoneDisplay: { title: '靈印足跡', description: '集齊八枚靈印，靈門即將開啟' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '醒來發現自己是隻貓',
            story: `好痛。全身都痛。\n\n而且……好像哪裡不太對。\n\n你試著睜開眼睛——視野低得離譜，像是趴在地上。空氣裡的味道撲面而來，濃烈得嚇人：泥土、腐葉、某種動物的體味、遠處溪水的濕氣……你確定自己的鼻子從來沒有這麼好用過。\n\n你想站起來，結果四肢一軟，臉先著地。\n\n……四肢？\n\n你低頭。兩隻毛茸茸的爪子。橘白相間的毛。\n\n你僵住了三秒鐘。然後你發瘋似地扭頭看自己的身體——一條尾巴。一條貨真價實的、橘色的、正在因為你的驚慌而炸毛的尾巴。\n\n「……喵？」\n\n你是一隻貓。你變成了一隻該死的橘貓。\n\n腦子裡突然出現一個聲音：\n\n『外來者，此處為翠谷。汝既已化獸，便守獸之規。違者……後果自負。』\n\n一隻比你大三倍的黑狗慢悠悠地踱過來，用一種「又來一個菜的」的表情嘆了口氣。`,
            WRD: '晴朗，微風穿林，花香混著泥土味',
            LOC: ['翠谷靈域', '東林', '醒魂坡'],
            PC: `${username}剛穿越，變成一隻橘貓，一臉懵，連走路都還不太會。`,
            NPC: [],
            timeOfDay: '晨露',
            morality: 0,
            yearName: '靈紀', year: 1, month: 3, day: 1,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '你變成了一隻橘貓，站在陌生的森林裡。一隻大黑狗正用看菜鳥的眼神打量你。'
        }),
    },

    hero: {
        id: 'hero',
        milestoneIds: ['M1_POWER_AWAKENING','M2_VILLAIN_CONTRACT','M3_HIDDEN_TRUTH','M4_RESONANCE_CRISIS','M5_SYSTEM_CRACK','M6_CHOICE_OF_SIDES','M7_FINAL_SESSION','M8_HOMECOMING'],
        milestoneChars: ['共','鳴','穿','透','黑','白','歸','心'],
        suggestionPrefix: '共情直覺低語：',
        questJournalDefault: '資料夾封面寫著：「個案代號：破曉。危險等級：S。」',
        name: '英雄',
        themeClass: 'hero-theme',
        defaultProfile: { yearName: '新紀元', year: 12, month: 6, day: 17, timeOfDay: '晨光時段' },
        moralityLabels: { positive: '正義', negative: '真相', axis: '信念立場' },
        milestoneDisplay: { title: '覺醒印記', description: '集齊八枚即可找到回家的路' },
        getInitialRound: (username) => ({
            R: 0,
            EVT: '醒在審訊室的穿越者',
            story: `你醒了。\n\n但這不是你的床。\n\n你躺在一張冰冷的金屬椅上，手腕被兩道發著淡藍色光芒的環扣固定在扶手上。頭頂是慘白的日光燈，對面是一面你用腳趾頭想都知道是單面鏡的玻璃牆。\n\n空氣裡有消毒水的味道。以及——某種微弱的電流嗡嗡聲。\n\n你最後的記憶是……在公司加班，第四杯咖啡喝到一半。然後就是一片空白。\n\n「編號S-0742，精神狀態掃描完成。」一個毫無感情的女聲從天花板的喇叭傳來。「請確認：你是否具有超自然能力？」\n\n「……什麼？」\n\n你還沒搞清楚狀況，眼角餘光就捕捉到牆上貼的海報——一個穿著藍金色緊身衣的男人，雙臂交叉，笑容燦爛得像牙膏廣告。海報上寫著：\n\n**『英雄管理局提醒您：未登記的異能使用屬於三級違規行為。』**\n\n你盯著海報上那個肌肉炸裂的男人看了五秒鐘，腦子裡只有一個想法：\n\n這件緊身衣，穿起來一定超級不透氣。\n\n然後審訊室的門開了。一個穿著深灰色制服、表情嚴肅得像是便秘第三天的中年男人走進來，把一個資料夾「啪」地拍在桌上。\n\n「你的異能反應測試呈陽性。恭喜，你現在是英雄管理局的管轄對象了。」\n\n他推了推眼鏡：「在你搞清楚怎麼用你的能力之前——你暫時被分配到D-7區，擔任在押異能犯罪者的……心理諮商師。」\n\n你：「……我一個穿越過來連狀況都搞不清楚的人，要去給超級反派做心理諮商？」\n\n他面無表情：「是的。你的第一位個案明天早上八點報到。」\n\n他留下資料夾，轉身走了。資料夾封面寫著：「個案代號：破曉。危險等級：S。」`,
            WRD: '室內，日光燈慘白',
            LOC: ['英雄管理局', '第七分局', 'D-7審訊室'],
            PC: `${username}剛穿越到超英世界，被關在審訊室，即將被指派為反派的心理諮商師。`,
            NPC: [],
            timeOfDay: '晨光時段',
            morality: 0,
            yearName: '新紀元', year: 12, month: 6, day: 17,
            playerState: 'alive',
            moralityChange: 0,
            suggestion: '資料夾上寫著你第一個諮商對象的代號：「破曉」，危險等級S。也許先翻開看看裡面寫了什麼。'
        }),
    },
};

export function getScenario(scenarioId) {
    return SCENARIOS[scenarioId] || SCENARIOS.wuxia;
}
